### ISSUE TITLE
Neotaci se hodinovy stroj

### ISSUE THREAD

**Issue by JanaKasparova** [UniversalScientificTechnologies/SolarCoelostat#15]
Po zapnuti ridiciho pocitace AROM se neotaci hodinovy stroj, tlacitka na zastaveni aspusteni hod.stroj funguji v tom smyslu,ze reaguje LCD display, stav hod. stroje to ale nezmeni. Nepomaha ani zmena nastaveni rychlost ve web.rozhrani. Prikladam snimek web.rozhrani s informacemi o stavu motoru.

![AROM_web_29o42022](https://user-images.githubusercontent.com/83455024/165908586-842b304a-fce3-4286-b938-f3b0f43cc434.png)

**Comment by JanaKasparova** [comment]
Znovu problem jako vyse. AROM kalibraci provede, ale hodinovy stroj se neotaci. Lze jej volne protocit rukou, zrejme neni pod napetim. V krabicce u hodinoveho stroje bylo premereno napeti,na 4 mistech neni, jak by melo byt, je nulove, viz mista oznacena X  na obrazku na odkaze. Dejte mi, prosim, vedet, kdy to bude mozne z vasi strany resit, pripadne, co muzu udelat ja. Predem dekuji.
![napeti](https://user-images.githubusercontent.com/83455024/180383496-de3dc20b-ccbd-4ab7-a075-a69c1520f108.png)

Snimek web.rozhrani:
![arom_22jul2022](https://user-images.githubusercontent.com/83455024/180417220-42be3413-ef3d-4e12-932d-c8dbf5b7bce6.png)

**Comment by ChroustJan** [comment]
Na napájecím modulu byla špatná 3A pojistka. Elektronické moduly byly bez zjevných poškození. Zkrat tam nebyl. Při normálním provozu odebírá elektronika 0,2A.  Příčina zničení pojistky nebyla nalezena. Aktuálně hodinový stroj funguje.
