### ISSUE TITLE
U spektrometru nelze nastavit integracni dobu vetsi nez 600 ms

### ISSUE THREAD

**Issue by roman-dvorak** [UniversalScientificTechnologies/SolarCoelostat#4]
### Popsaný problém po emailu

Spektrometry: U obou spektrometru nelze nastavit integracni dobu vetsi nez 600 ms. Po nastaveni vetsiho integracniho casu nedochazi ani k zobrazeni spekter v grafickem okne ani ukladani dat do HDF souboru (pri zapnutem recording). To je jine chovani nez vloni, kdy pro testovaci ucely byly bezne pouzivany integracni doby vetsi nez 600 ms. U obou spektrometru byly prekontrolovany kabely.

**Comment by roman-dvorak** [comment]
Je možné, že nastavení vyšší integrační doby nelze v kombinaci s dalším parametrem. Tohle musím zjistit na místě se spektroskopem. Bez spektroskopu to nemám jak zjistit, protože nemám k tomu dostatečnou dokumentaci komunikačního protokolu.

**Comment by JanaKasparova** [comment]
Dnes se menila jen integracni doba, ostatni parametry by mely mit zakladni nastaveni.

**Comment by roman-dvorak** [comment]
![Snímek obrazovky pořízený 2021-06-13 15-42-24](https://user-images.githubusercontent.com/5196729/121809669-f8047a80-cc5d-11eb-9e9e-b4d471aa26e8.png)

Delší expoziční doba nyní lze nastavit. Problém byl v tom, že v průběhu expozice spektroskop neodpovídá na žádné požadavky a nějaký nízkoúrovňový driver (zajišťující komunikaci po USB) pak končil na timeout. 

Na obrázku je vidět měření s expozicí 1 a 5s (zároveň). Otestována byla i 10s expozice. 

S touto úpravou byly vyřešeny dvě vylepšení: 
* Nastavení spektroskopu se po spuštění nastaví dle posledního použitého (především expoziční čas) 
* Interni korekce (dark-noise) lze přepínat tlačítkem v UI. 


Fungování bylo otestováno.
