### ISSUE TITLE
Kalibrace po vyjetí z rozsahu nelze opakovat

### ISSUE THREAD

**Issue by roman-dvorak** [UniversalScientificTechnologies/SolarCoelostat#5]
K dořešení:
- [x] Upravení kalibrace
- [x] Otestování upravené kalibrace
- [x] Dopsání návodu
---

Pokud dojde v průběhu provozu k vyjetí z provozního rozsahu (stačí pouze ze SW rozsahu nebo až po najetí na tlačítko?? @ChroustJan), tak při vystředění a následné kalibraci neproběhne kalibrace v pořádku. Zůstane u horního koncového spínače (viz obrázek). Driver si i tak myslí, že z koncáku odjel (podle polohy) koncák je však stále sepnutý. V tomto stavu je nutné systém vypnout, vycentrovat a po zapnutí provést kalibraci. 

![179195649_3936900756422904_8441592817861762793_n](https://user-images.githubusercontent.com/5196729/116687297-3519f380-a9b5-11eb-9c24-ffd8f4d61eb9.jpg)

Zřejmě se něco při opakované kalibraci nezinicializuje správně. Je toto chování potřeba detailněji prozkoumat z pohledu driveru (jeho předpokládaná poloha, stav koncového spínače, ztracné kroky, atd..)

**Comment by JanaKasparova** [comment]
V pondeli 26.4.2021 nepomohlo ani system vypnout, manualne vycentrovat a spustit kalibraci. Kalibrace vzdy skoncila v poloze, jak je na obrazku. Dnes vse v poradku.

**Comment by roman-dvorak** [comment]
Předělal jsem způsob kalibrace tak, že se nyní kontroluje odjetí od koncových spínačů. A nemělo by nyní docházet k zastavení při rozepnutí spínače. Kalibrace teď opakovaně fungovala. 

Ve stručnosti nyní funguje takto:
#### 1. krok
Pokud je coelostat na koncovém spínači, systém odmítne kalibraci hláškou na LCD. Je to potřeba ručně dostat ze spínačů a následně kalibraci spustit znovu. 

#### 2. krok
 * Spustí se hodinový stroj
 * Oba motory zároveň dojedou na spodní koncové spínače. 

#### 3. krok
 * Obě osy přejedou na horní koncové spínače. 
 * Systém si změří vzdálenost, mezi koncovými spínači

#### 4. krok
 * Obě osy se vrátí do změřené poloviny celého pracovního rozsahu

Tím je kalibrace dokončena.

**Comment by roman-dvorak** [comment]
Původní oprava obsahovala problém, že při kalibraci se restartovaly drivery. To způsobilo, mimo jiné, i nastavení výchozí maximální rychlosti, které je menší než je potřebná rychlost pro motor denního pohybu.

Zřejmě aktuální implementace kalibrace funguje a vytváří o dost větší pracovní rozsah než původní.
