### ISSUE TITLE
nefunkcni slit-jaw kamera

### ISSUE THREAD

**Issue by JanaKasparova** [UniversalScientificTechnologies/SolarCoelostat#8]
Okno se slit-jaw snimkem se neaktualizuje, tj. pokud se na plose prekryje s ikonkami, zustavaji v nem zobrazene ikonky, viz priloha a okno slit-jaw kamery vpravo.
![nefunkcni_sjkamera](https://user-images.githubusercontent.com/83455024/121894455-72490380-cd1f-11eb-953d-2de9049e440b.png)
Neni jasne, zda je nefukcni software nebo kamera. Kabely byly zkontrolovany a odpojeny a znovu pripojeny.

**Comment by JanaKasparova** [comment]
Otestovano, ze kamera je sama o sobe funkcni z Win programem Sharpcap. Ovladaci SW se ale chova jako popsano vyse. Pokud na terminalu spoustim radek po radku prikazy uvedene ve scriptu umistenem na Plose PC /home/roman/arom_ws/src/SolarCoelostat/tools/slitjaw_camera  , posledni prikaz 

rosrun solar_coelostat obs_slitjaw

vede k temto hlaskam (vypisuji jen posledni)

(python:2927): GLib-CRITICAL **: g_main_context_push_thread_default: assertion 'acquired_context' failed
QObject::killTimer: Timers cannot be stopped from another thread

Po zmacknuti tlacitka "exit"  na ovladacim panelu se vypise toto:

QObject::killTimer: Timers cannot be stopped from another thread
Zacinam se ukoncovat
Neoprávněný přístup do paměti (SIGSEGV) (core dumped [obraz paměti uložen])

**Comment by roman-dvorak** [comment]
Zřejmě způsobeno aktualizací OpenCV. Software byl předělán, aby nepoužíval pro vykreslování OpenCV.
